apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustermetadatas.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: ClusterMetadata
    plural: clustermetadatas
    singular: clustermetadata
    shortNames:
      - clustermeta
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                  nullable: false
                clusterRegion:
                  type: string
                  nullable: false
                clusterGroup:
                  type: string
                  nullable: false
                servicePhase:
                  type: string
                  nullable: false
                serviceTag:
                  type: string
                  nullable: false
                clusterType:
                  type: string
                  nullable: false
                clusterEngine:
                  type: string
                  nullable: false
                infraVendor:
                  type: string
                  nullable: false
                infraAccountId:
                  type: string
                  nullable: false
              required:
                - clusterName
                - clusterRegion
                - clusterGroup
                - servicePhase
                - serviceTag
                - clusterType
                - clusterEngine
                - infraVendor
                - infraAccountId
      additionalPrinterColumns:
        - name: ClusterRegion
          type: string
          jsonPath: ".spec.clusterRegion"
        - name: ClusterGroup
          type: string
          jsonPath: ".spec.clusterGroup"
        - name: ClusterType
          type: string
          jsonPath: ".spec.clusterType"
