// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api_resources/resources.proto

package api_resources

import (
	context "context"
	idl_common "github.com/krafton-hq/red-fox/apis/idl_common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomDocumentDefinitionServerClient is the client API for CustomDocumentDefinitionServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomDocumentDefinitionServerClient interface {
	ListApiResources(ctx context.Context, in *idl_common.CommonReq, opts ...grpc.CallOption) (*ListApiResourcesRes, error)
}

type customDocumentDefinitionServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomDocumentDefinitionServerClient(cc grpc.ClientConnInterface) CustomDocumentDefinitionServerClient {
	return &customDocumentDefinitionServerClient{cc}
}

func (c *customDocumentDefinitionServerClient) ListApiResources(ctx context.Context, in *idl_common.CommonReq, opts ...grpc.CallOption) (*ListApiResourcesRes, error) {
	out := new(ListApiResourcesRes)
	err := c.cc.Invoke(ctx, "/redfox.api.api_resources.CustomDocumentDefinitionServer/ListApiResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomDocumentDefinitionServerServer is the server API for CustomDocumentDefinitionServer service.
// All implementations must embed UnimplementedCustomDocumentDefinitionServerServer
// for forward compatibility
type CustomDocumentDefinitionServerServer interface {
	ListApiResources(context.Context, *idl_common.CommonReq) (*ListApiResourcesRes, error)
	mustEmbedUnimplementedCustomDocumentDefinitionServerServer()
}

// UnimplementedCustomDocumentDefinitionServerServer must be embedded to have forward compatible implementations.
type UnimplementedCustomDocumentDefinitionServerServer struct {
}

func (UnimplementedCustomDocumentDefinitionServerServer) ListApiResources(context.Context, *idl_common.CommonReq) (*ListApiResourcesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApiResources not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) mustEmbedUnimplementedCustomDocumentDefinitionServerServer() {
}

// UnsafeCustomDocumentDefinitionServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomDocumentDefinitionServerServer will
// result in compilation errors.
type UnsafeCustomDocumentDefinitionServerServer interface {
	mustEmbedUnimplementedCustomDocumentDefinitionServerServer()
}

func RegisterCustomDocumentDefinitionServerServer(s grpc.ServiceRegistrar, srv CustomDocumentDefinitionServerServer) {
	s.RegisterService(&CustomDocumentDefinitionServer_ServiceDesc, srv)
}

func _CustomDocumentDefinitionServer_ListApiResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(idl_common.CommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).ListApiResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.api_resources.CustomDocumentDefinitionServer/ListApiResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).ListApiResources(ctx, req.(*idl_common.CommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomDocumentDefinitionServer_ServiceDesc is the grpc.ServiceDesc for CustomDocumentDefinitionServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomDocumentDefinitionServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redfox.api.api_resources.CustomDocumentDefinitionServer",
	HandlerType: (*CustomDocumentDefinitionServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApiResources",
			Handler:    _CustomDocumentDefinitionServer_ListApiResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_resources/resources.proto",
}
