// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: crds/service.proto

package crds

import (
	context "context"
	idl_common "github.com/krafton-hq/red-fox/apis/idl_common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomDocumentDefinitionServerClient is the client API for CustomDocumentDefinitionServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomDocumentDefinitionServerClient interface {
	GetCustomResourceDefinition(ctx context.Context, in *idl_common.SingleObjectReq, opts ...grpc.CallOption) (*GetCustomResourceDefinitionRes, error)
	ListCustomResourceDefinitions(ctx context.Context, in *idl_common.ListObjectReq, opts ...grpc.CallOption) (*ListCustomResourceDefinitionsRes, error)
	CreateCustomResourceDefinition(ctx context.Context, in *CreateCustomResourceDefinitionReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error)
	UpdateCustomResourceDefinition(ctx context.Context, in *UpdateCustomResourceDefinitionReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error)
	DeleteCustomResourceDefinition(ctx context.Context, in *idl_common.SingleObjectReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error)
}

type customDocumentDefinitionServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomDocumentDefinitionServerClient(cc grpc.ClientConnInterface) CustomDocumentDefinitionServerClient {
	return &customDocumentDefinitionServerClient{cc}
}

func (c *customDocumentDefinitionServerClient) GetCustomResourceDefinition(ctx context.Context, in *idl_common.SingleObjectReq, opts ...grpc.CallOption) (*GetCustomResourceDefinitionRes, error) {
	out := new(GetCustomResourceDefinitionRes)
	err := c.cc.Invoke(ctx, "/redfox.api.crds.CustomDocumentDefinitionServer/GetCustomResourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customDocumentDefinitionServerClient) ListCustomResourceDefinitions(ctx context.Context, in *idl_common.ListObjectReq, opts ...grpc.CallOption) (*ListCustomResourceDefinitionsRes, error) {
	out := new(ListCustomResourceDefinitionsRes)
	err := c.cc.Invoke(ctx, "/redfox.api.crds.CustomDocumentDefinitionServer/ListCustomResourceDefinitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customDocumentDefinitionServerClient) CreateCustomResourceDefinition(ctx context.Context, in *CreateCustomResourceDefinitionReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error) {
	out := new(idl_common.CommonRes)
	err := c.cc.Invoke(ctx, "/redfox.api.crds.CustomDocumentDefinitionServer/CreateCustomResourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customDocumentDefinitionServerClient) UpdateCustomResourceDefinition(ctx context.Context, in *UpdateCustomResourceDefinitionReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error) {
	out := new(idl_common.CommonRes)
	err := c.cc.Invoke(ctx, "/redfox.api.crds.CustomDocumentDefinitionServer/UpdateCustomResourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customDocumentDefinitionServerClient) DeleteCustomResourceDefinition(ctx context.Context, in *idl_common.SingleObjectReq, opts ...grpc.CallOption) (*idl_common.CommonRes, error) {
	out := new(idl_common.CommonRes)
	err := c.cc.Invoke(ctx, "/redfox.api.crds.CustomDocumentDefinitionServer/DeleteCustomResourceDefinition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomDocumentDefinitionServerServer is the server API for CustomDocumentDefinitionServer service.
// All implementations must embed UnimplementedCustomDocumentDefinitionServerServer
// for forward compatibility
type CustomDocumentDefinitionServerServer interface {
	GetCustomResourceDefinition(context.Context, *idl_common.SingleObjectReq) (*GetCustomResourceDefinitionRes, error)
	ListCustomResourceDefinitions(context.Context, *idl_common.ListObjectReq) (*ListCustomResourceDefinitionsRes, error)
	CreateCustomResourceDefinition(context.Context, *CreateCustomResourceDefinitionReq) (*idl_common.CommonRes, error)
	UpdateCustomResourceDefinition(context.Context, *UpdateCustomResourceDefinitionReq) (*idl_common.CommonRes, error)
	DeleteCustomResourceDefinition(context.Context, *idl_common.SingleObjectReq) (*idl_common.CommonRes, error)
	mustEmbedUnimplementedCustomDocumentDefinitionServerServer()
}

// UnimplementedCustomDocumentDefinitionServerServer must be embedded to have forward compatible implementations.
type UnimplementedCustomDocumentDefinitionServerServer struct {
}

func (UnimplementedCustomDocumentDefinitionServerServer) GetCustomResourceDefinition(context.Context, *idl_common.SingleObjectReq) (*GetCustomResourceDefinitionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomResourceDefinition not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) ListCustomResourceDefinitions(context.Context, *idl_common.ListObjectReq) (*ListCustomResourceDefinitionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCustomResourceDefinitions not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) CreateCustomResourceDefinition(context.Context, *CreateCustomResourceDefinitionReq) (*idl_common.CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomResourceDefinition not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) UpdateCustomResourceDefinition(context.Context, *UpdateCustomResourceDefinitionReq) (*idl_common.CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomResourceDefinition not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) DeleteCustomResourceDefinition(context.Context, *idl_common.SingleObjectReq) (*idl_common.CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomResourceDefinition not implemented")
}
func (UnimplementedCustomDocumentDefinitionServerServer) mustEmbedUnimplementedCustomDocumentDefinitionServerServer() {
}

// UnsafeCustomDocumentDefinitionServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomDocumentDefinitionServerServer will
// result in compilation errors.
type UnsafeCustomDocumentDefinitionServerServer interface {
	mustEmbedUnimplementedCustomDocumentDefinitionServerServer()
}

func RegisterCustomDocumentDefinitionServerServer(s grpc.ServiceRegistrar, srv CustomDocumentDefinitionServerServer) {
	s.RegisterService(&CustomDocumentDefinitionServer_ServiceDesc, srv)
}

func _CustomDocumentDefinitionServer_GetCustomResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(idl_common.SingleObjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).GetCustomResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.crds.CustomDocumentDefinitionServer/GetCustomResourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).GetCustomResourceDefinition(ctx, req.(*idl_common.SingleObjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomDocumentDefinitionServer_ListCustomResourceDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(idl_common.ListObjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).ListCustomResourceDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.crds.CustomDocumentDefinitionServer/ListCustomResourceDefinitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).ListCustomResourceDefinitions(ctx, req.(*idl_common.ListObjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomDocumentDefinitionServer_CreateCustomResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomResourceDefinitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).CreateCustomResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.crds.CustomDocumentDefinitionServer/CreateCustomResourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).CreateCustomResourceDefinition(ctx, req.(*CreateCustomResourceDefinitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomDocumentDefinitionServer_UpdateCustomResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomResourceDefinitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).UpdateCustomResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.crds.CustomDocumentDefinitionServer/UpdateCustomResourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).UpdateCustomResourceDefinition(ctx, req.(*UpdateCustomResourceDefinitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomDocumentDefinitionServer_DeleteCustomResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(idl_common.SingleObjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDocumentDefinitionServerServer).DeleteCustomResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redfox.api.crds.CustomDocumentDefinitionServer/DeleteCustomResourceDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDocumentDefinitionServerServer).DeleteCustomResourceDefinition(ctx, req.(*idl_common.SingleObjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomDocumentDefinitionServer_ServiceDesc is the grpc.ServiceDesc for CustomDocumentDefinitionServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomDocumentDefinitionServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redfox.api.crds.CustomDocumentDefinitionServer",
	HandlerType: (*CustomDocumentDefinitionServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomResourceDefinition",
			Handler:    _CustomDocumentDefinitionServer_GetCustomResourceDefinition_Handler,
		},
		{
			MethodName: "ListCustomResourceDefinitions",
			Handler:    _CustomDocumentDefinitionServer_ListCustomResourceDefinitions_Handler,
		},
		{
			MethodName: "CreateCustomResourceDefinition",
			Handler:    _CustomDocumentDefinitionServer_CreateCustomResourceDefinition_Handler,
		},
		{
			MethodName: "UpdateCustomResourceDefinition",
			Handler:    _CustomDocumentDefinitionServer_UpdateCustomResourceDefinition_Handler,
		},
		{
			MethodName: "DeleteCustomResourceDefinition",
			Handler:    _CustomDocumentDefinitionServer_DeleteCustomResourceDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crds/service.proto",
}
