apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: Cluster
    plural: clusters
    singular: cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                  nullable: false
                clusterRegion:
                  type: string
                  nullable: false
                clusterGroup:
                  type: string
                  nullable: false
                servicePhase:
                  type: string
                  nullable: false
                serviceTag:
                  type: string
                  nullable: false
                clusterEngine:
                  type: string
                  nullable: false
                infraVendor:
                  type: string
                  nullable: false
                infraAccountId:
                  type: string
                  nullable: false
              required:
                - clusterName
                - clusterRegion
                - clusterGroup
                - servicePhase
                - serviceTag
                - clusterEngine
                - infraVendor
                - infraAccountId
            status:
              type: object
              properties:
                apiserver:
                  type: object
                  properties:
                    endpoint:
                      type: string
                      nullable: false
                    caCert:
                      type: string
                      nullable: false
                serviceAccountIssuer:
                  type: string
                  nullable: false
                awsIamIdps:
                  type: object
                  additionalProperties:
                    type: string
                    nullable: false
              required:
                - apiserver
                - serviceAccountIssuer
          required:
            - spec
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: ClusterRegion
          type: string
          jsonPath: ".spec.clusterRegion"
        - name: ClusterGroup
          type: string
          jsonPath: ".spec.clusterGroup"
