apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressaddresses.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: IngressAddress
    plural: ingressaddresses
    singular: ingressaddress
    shortNames:
      - ingaddr
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                default:
                  type: object
                  properties:
                    host:
                      type: string
                      nullable: false
                    port:
                      type: number
                      nullable: false
                    protocol:
                      type: string
                      nullable: false
                  required:
                    - host
                    - port
                    - protocol
                specs:
                  type: object
                  properties:
                    hosts:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        nullable: false
                    ports:
                      type: array
                      minItems: 1
                      items:
                        type: number
                        nullable: false
                    protocols:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        nullable: false
                  required:
                    - hosts
                    - ports
                    - protocols
              required:
                - default
                - specs
      additionalPrinterColumns:
        - name: Host
          type: string
          jsonPath: ".spec.default.host"
        - name: Protocol
          type: string
          jsonPath: ".spec.default.protocol"
        - name: Labels
          type: string
          jsonPath: ".metadata.labels"
