apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressaddresses.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: IngressAddress
    plural: ingressaddresses
    singular: ingressaddress
    shortNames:
      - ingaddr
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                urls:
                  type: array
                  minItems: 1
                  items:
                    type: string
                    nullable: false
              required:
                - urls
      additionalPrinterColumns:
        - name: Urls
          type: string
          jsonPath: ".spec.urls"
        - name: Labels
          type: string
          jsonPath: ".metadata.labels"
