apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: latestversions.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: LatestVersion
    plural: latestversions
    singular: latestversion
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRef:
                  type: object
                  properties:
                    branch:
                      type: string
                      nullable: false
                    repository:
                      type: string
                      nullable: false
                  required:
                    - branch
                    - repository
              required:
                - gitRef
            status:
              type: object
              properties:
                versionRef:
                  type: object
                  properties:
                    name:
                      type: string
                      nullable: false
                  required:
                    - name
              required:
                - versionRef
          required:
            - spec
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Repository
          jsonPath: ".spec.gitRef.repository"
          type: string
        - name: Branch
          jsonPath: ".spec.gitRef.branch"
          type: string
        - name: Version
          jsonPath: ".status.versionRef.name"
          type: string
