apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: versioncounts.metadata.sbx-central.io
spec:
  group: metadata.sbx-central.io
  scope: Namespaced
  names:
    kind: VersionCount
    plural: versioncounts
    singular: versioncount
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: number
                  nullable: false
                projectName:
                  type: string
                  nullable: false
              required:
                - count
                - projectName
      additionalPrinterColumns:
        - name: Project
          jsonPath: ".spec.projectName"
          type: string
        - name: Count
          jsonPath: ".spec.count"
          type: number
